1Route:
   path: %databaseconnector/fuck/\d%i
   method: GET
   controller: UserController
   contrMethod: getUser
2Route:
   path: %databaseconnector/2bla/\d%i
   method: GET
   controller: 2UserController
   contrMethod: getUser
3Route:
   path: %databaseconnector/bla/\d%i
   method: GET
   controller: 3UserController
   contrMethod: getUser
