get_user:
   pattern: %api/user/\d%i
   method: GET
   controller: UserController
   controllerMethod: getUser
   controllerNameSpace: ApiBundle\Controller\
   countMethodArguments: 1

create_user:
   pattern: %api/user/create%i
   method: POST
   controller: UserController
   controllerMethod: createUser
   controllerNameSpace: ApiBundle\Controller\
   countMethodArguments: 0

delete_user:
   pattern: %api/user/\d%i
   method: DELETE
   controller: UserController
   controllerMethod: deleteUser
   controllerNameSpace: ApiBundle\Controller\
   countMethodArguments: 1

get_role:
   pattern: %api/role/\d%i
   method: GET
   controller: RoleController
   controllerMethod: getRole
   controllerNameSpace: ApiBundle\Controller\
   countMethodArguments: 1

get_random:
   pattern: %api/wtf/\d%i
   method: GET
   controller: OneMoreController
   controllerMethod: getRand
   controllerNameSpace: ApiBundle\Controller\
   countMethodArguments: 1
