get_user:
   pattern: %api/user/\d%i
   method: GET
   controller: UserController
   controllerMethod: getUser
   controllerNameSpace: ApiBundle\Controller\
   countMethodArguments: 1

get_role:
   pattern: %api/role/\d%i
   method: GET
   controller: RoleController
   controllerMethod: getRole
   controllerNameSpace: ApiBundle\Controller\
   countMethodArguments: 1

get_random:
   pattern: %api/wtf/\d%i
   method: GET
   controller: OneMoreController
   controllerMethod: getRand
   controllerNameSpace: ApiBundle\Controller\
   countMethodArguments: 1
